DROP DATABASE IF EXISTS CAR_HIRE_MANAGEMENT;
CREATE DATABASE CAR_HIRE_MANAGEMENT;

USE CAR_HIRE_MANAGEMENT;

DROP TABLE IF EXISTS CUSTOMER;
CREATE TABLE CUSTOMER (
    customer_id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    phone_number VARCHAR(20) NOT NULL UNIQUE,
    email VARCHAR(255) NOT NULL UNIQUE
);