version: '1'

services:
  mysql-server:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password123
      MYSQL_PASSWORD: password123

    ports:
      - '3307:3306'
    volumes:
      - ./../queries/CREATE_DATABASE.sql:/docker-entrypoint-initdb.d/CREATE_DATABASE.sql
  car_hire_management:
    image: abhi94n/car_hire_management:latest
    environment:
      FLASK_DEBUG: '1'
      MYSQL_HOST: host.docker.internal
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: password123
      MYSQL_PASSWORD: password123
      MYSQL_DB: CAR_HIRE_MANAGEMENT
      MYSQL_PORT: 3307
      APP_PORT: 5000
    ports:
      - '5000:5000'
    depends_on:
      - mysql-server
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - '8080:80'
    environment:
      PMA_HOST: mysql-server
    depends_on:
      - mysql-server
